---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3
  - name: debian-9
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[java::default]
      - recipe[sips-office-server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      java:
        openjdk_packages: ['default-jre-headless']
      sips-office-server:
        service:
          acl:
            accept:
              - 0.0.0.0
            deny:
              - 1.1.1.1
        command:
          acl:
            accept:
              - 0.0.0.0
            deny:
              - 1.1.1.1
        http_request:
          acl:
            accept:
              - 0.0.0.0
            deny:
              - 1.1.1.1